### ISSUE TITLE
Question: Filenames?

### ISSUE THREAD

**Issue by BillyCroan** [mindbit/mb2md#1]
Why are the filenames generated, seemingly random?

Could the MessageID be used instead?  Or Perhaps YYYYMMDDHHMMSS-MessageID?

I'm just curious if there's an reason it needs to be random/sequential here before I go and try to modify it.

**Comment by rrendec** [comment]
To be honest, I have no idea - it was like this when I imported it from dovecot.org. But I think it's not random. I did a quick test on a 3 messages mbox, and got this:

```
1704482685.000000.mbox:2,
1704482685.000001.mbox:2,
1704482685.000002.mbox:2,
```

The first part (before the first dot) is a UNIX timestamp. This seems to be consistent with what Postfix does when it delivers mail to a Maildir. It's also consistent with what Dovecot expects, so if you change it, I would suggest to check if it's still compatible with your IMAP server.

There is something about this in the Dovecot documentation: https://doc.dovecot.org/admin_manual/mailbox_formats/maildir/#filename-examples

**Comment by BillyCroan** [comment]
you're right!  The filenaming convention comes fro dovecot and UofW.  I ended up writing my own script to extract the way I wanted for archival.  mb2md isn't exactly meant for archival.  

There's a reason they didn't use any part of the message in the filename:  Email, even the headers, are messy as sin.  I see now why they did it that way.  So many edge cases and "creativity"....  

If I can't get my script to run without error in the next day I'm gonna save to files named after a hash of the contents.  and STILL I'll have a little fear the first time I run it that SOMEHOW some lunatic message will produce an emoji or unicode in the output of the hash.

Thanks for helping me realize this.
